#!/bin/sh
# description: Start or stop the MQTT action daemon
# *********************************************************************************** *
# Copyright 2017 by Bodo Bauer <bb@bb-zone.com>
#
# This file is part of the RPI Sensor Client
#
# ReadDHT11 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MQTTActionD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ReadDHT11.  If not, see <http://www.gnu.org/licenses/>.
# *********************************************************************************** *
### BEGIN INIT INFO
# Provides:             mqttactiond
# Required-Start:       $local_fs $remote_fs
# Required-Stop:        $local_fs $remote_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    MQTT action daemon
### END INIT INFO

BIN=/usr/sbin/rpisensorclient
make in
case "$1" in
'start')
  echo "Starting sensor client..."
  $BIN -c $CNF
  RETVAL=$?
;;

'stop')
  echo "Stopping sensor client..."
  kill `cat $PID`
  RETVAL=$?
;;

'status')
  cnt=`ps -ef | grep "rpisensorclient" | grep -v grep | wc -l`
  if [ "$cnt" -eq "0" ] ; then
    echo "Sensor client is not running"
  else
    echo "Sensor client is running"
  fi
;;

*)
  echo "Usage: $0 { start | stop | status }"
  RETVAL=1
;;

esac
exit $RETVAL
